name: "ChainAlert"

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 1 * * *'

jobs:
  chainalert:
    name: ChainAlert
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: checkmarx/chainalert-github-action@master
